apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: sentinel-deployment
spec:
  selector:
    matchLabels:
      app: sentinel
  replicas: 2
  template:
    metadata:
      labels:
        app: sentinel
    spec:
      containers:
      - name: sentinel
        image: sentinel
        ports:
        - containerPort: 8858