spring:
  application:
    name: gateway
  #需要将这个服务注册到Nacos中
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848   #nacos的服务注册中心
    gateway:
      routes:
          - id: host_route
            uri: http://localhost:8070/admin
            predicates:
              - Path=/admin/**
    sentinel:
      transport:
        # sentinel服务端地址
        dashboard: localhost:8858  #sentinel的控制台
        client-ip: localhost
      eager: true
server:
  port: 8097
