apiVersion: v1
kind: Service
metadata:
  name: mongo-dev
  namespace: default
spec:
  clusterIP: 10.96.2.126 #固定clusterIP
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
 - port: 9090
    targetPort: 9090
    protocol: TCP
