apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: admin-deployment
spec:
  selector:
    matchLabels:
      app:admin
  replicas: 2
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
      - name: admin
        image: admin
        ports:
        - containerPort: 8070