apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: common-deployment
spec:
  selector:
    matchLabels:
      app:common
  replicas: 2
  template:
    metadata:
      labels:
        app: common
    spec:
      containers:
      - name: common
        image: common
        ports:
        - containerPort: 8070